SELECT
    f1.FLAVOR
FROM
    FIRST_HALF f1
JOIN
    ICECREAM_INFO f2
ON
    f1.FLAVOR = f2.FLAVOR
WHERE
    TOTAL_ORDER > 3000 AND
    f2.INGREDIENT_TYPE = 'fruit_based'
ORDER BY
    f1.TOTAL_ORDER desc;